version: 2.1
executors:
  node-postgres:
    docker:
      - image: circleci/node:8.14.0
        environment:
            DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
            POSTGRES_PASSWORD: ""
            DATABASE_URL: postgres://root@localhost:5432/circle_test
    working_directory: ~/repo
jobs:
  test:
    executor: node-postgres
    steps:
      - run:
          name: Clone repository over HTTPS
          command: git clone https://github.com/agmodelsystems/translation.git .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    executor: node-postgres
    steps:
      - run:
          name: Clone repository over HTTPS
          command: git clone https://github.com/agmodelsystems/translation.git .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run deploy
workflows:
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
